### ISSUE TITLE
RunVid.scala: class ButtonBuilder in package control is deprecated

### ISSUE THREAD

**Issue by EwoutH** [NetLogo/Vid-Extension#25]
I noticed a compile warning in [RunVid.scala#L49](https://github.com/NetLogo/Vid-Extension/blob/hexy/src/main/scala/RunVid.scala#L49) during a [CI run](https://github.com/NetLogo/NetLogo/runs/4091529606?check_suite_focus=true#step:7:453).
```
[warn] /home/runner/work/NetLogo/NetLogo/extensions/vid/src/main/scala/RunVid.scala:49:20: class ButtonBuilder in package control is deprecated
[warn]           val bb = ButtonBuilder.create()
[warn]                    ^
[warn] one warning found
```

**Comment by brandesNW** [comment]
Fixed by commit 69e422a2474a
Author: Aaron Andre Brandes <aaron.brandes@northwestern.edu>
Date:   Tue Feb 1 12:47:45 2022 -0500

    remove deprecated method ButtonBuilder
